#!/bin/bash
# Copyright (C) 2013  Sotirios Vrachas
# inspired from lightsOn.sh iye.cba at gmail com
# url: https://github.com/iye/lightsOn

displays=""
while read id
do
    displays="$displays $id"
done< <(xvinfo | sed -n 's/^screen #\([0-9]\+\)$/\1/p')

# loop through every display looking for a fullscreen window
for display in $displays
do
    #get id of active window and clean output
    activ_win_id=`DISPLAY=:0.${display} xprop -root _NET_ACTIVE_WINDOW`
    #activ_win_id=${activ_win_id#*# } #gives error if xprop returns extra ", 0x0" (happens on some distros)
    activ_win_id=${activ_win_id:40:9}        
    # Check if Active Window (the foremost window) is in fullscreen state
    isActivWinFullscreen=`DISPLAY=:0.${display} xprop -id $activ_win_id _NET_WM_STATE | grep _NET_WM_STATE_FULLSCREEN`
        if [[ "$isActivWinFullscreen" = *NET_WM_STATE_FULLSCREEN* ]];then
            xtrlock
            exit 0
        fi
done
slock
exit 0
